<script lang="ts">
  import { ArrowLeft, BookOpenCheck, Braces, Building2, CalendarSync, CheckCircle2, ChevronRight, FileJson2, FileSpreadsheet, Globe2, Link2, LoaderCircle, RefreshCw, Search, TriangleAlert, ShieldCheck, UploadCloud, X } from 'lucide-svelte';
  import { closeShiguangSession, commitImport, getShiguangSession, importText, listShiguangAdapters, listShiguangSchools, startShiguangImport } from '../tauri';
  import type { ImportBundle, ShiguangAdapter, ShiguangImportStart, ShiguangSchool } from '../types'; import { createEventDispatcher, onDestroy } from 'svelte';
  const dispatch = createEventDispatcher<{ imported: void }>();
  const sources = [
    { icon: Globe2, title: '高校教务系统', subtitle: '从开放适配仓库搜索学校并网页登录教务', tag: '推荐', accent: 'violet', action: 'shiguang' },
    { icon: CalendarSync, title: '拾光适配器', subtitle: '直接兼容 shiguang_warehouse，自动获取作息和开学日期', tag: '生态兼容', accent: 'cyan', action: 'shiguang' },
    { icon: FileJson2, title: 'WakeUp / JSON / CSES', subtitle: '分享文本、备份文件、通用 JSON 与 CSES YAML', tag: '自动识别', accent: 'amber', action: 'file' },
    { icon: FileSpreadsheet, title: 'Excel / CSV', subtitle: 'XLSX、CSV、TSV 表格课表', tag: '结构映射', accent: 'green', action: 'file' },
    { icon: BookOpenCheck, title: 'ICS / 系统日历', subtitle: '导入 iCalendar，也可绑定系统日历', tag: '跨平台', accent: 'blue', action: 'file' },
    { icon: Braces, title: '开发者适配器', subtitle: '安装本地或远程签名 Adapter 包', tag: '高级', accent: 'pink', action: 'developer' }
  ];
  let fileInput: HTMLInputElement; let loading = false; let dragOver = false; let preview: ImportBundle | null = null; let selectedFile = ''; let error = ''; let committed = '';
  let shiguangOpen = false; let shiguangLoading = false; let shiguangError = ''; let schoolQuery = ''; let schools: ShiguangSchool[] = []; let selectedSchool: ShiguangSchool | null = null; let adapters: ShiguangAdapter[] = []; let activeSession: ShiguangImportStart | null = null; let sessionMessage = ''; let pollTimer: ReturnType<typeof setTimeout> | null = null;
  $: normalizedSchoolQuery = schoolQuery.trim().toLowerCase();
  $: filteredSchools = schools.filter((school) => !normalizedSchoolQuery || school.name.toLowerCase().includes(normalizedSchoolQuery) || school.id.toLowerCase().includes(normalizedSchoolQuery) || school.initial.toLowerCase().includes(normalizedSchoolQuery)).sort((a,b) => Number(b.id === 'GDUT') - Number(a.id === 'GDUT') || a.initial.localeCompare(b.initial, 'zh-CN')).slice(0,80);
  function formatFor(name: string) { const ext = name.toLowerCase().split('.').pop() ?? ''; if (ext === 'json') return 'json'; if (ext === 'ics' || ext === 'ical') return 'ics'; if (ext === 'csv' || ext === 'tsv') return ext; if (ext === 'cses' || ext === 'yaml' || ext === 'yml') return 'cses'; return ext; }
  async function loadFile(file?: File) {
    if (!file) return; error=''; committed=''; preview=null; selectedFile=file.name; const format=formatFor(file.name);
    if (!['json','ics','csv','tsv','cses'].includes(format)) { error = format === 'xlsx' || format === 'xls' ? 'XLS/XLSX 解析器接口已经预留；先使用 CSV/TSV，后续会接 calamine 原生解析。' : `暂不识别 .${format || 'unknown'} 文件。`; return; }
    loading=true; try { preview = await importText(format, await file.text()); } catch(e) { error=e instanceof Error ? e.message : String(e); } finally { loading=false; }
  }
  async function commitPreview() { if(!preview)return; loading=true; error=''; try { const result=await commitImport(preview); committed=`已创建新课表：${result.courseCount} 门课程 / ${result.meetingCount} 个上课时段。`; preview=null; dispatch('imported'); } catch(e){ error=e instanceof Error?e.message:String(e); } finally { loading=false; } }
  function onDrop(event: DragEvent){ event.preventDefault(); dragOver=false; loadFile(event.dataTransfer?.files?.[0]); }
  async function openShiguang(){ shiguangOpen=true; shiguangError=''; if(schools.length)return; shiguangLoading=true; try{schools=await listShiguangSchools();}catch(e){shiguangError=e instanceof Error?e.message:String(e);}finally{shiguangLoading=false;} }
  async function chooseSchool(school: ShiguangSchool){selectedSchool=school;adapters=[];shiguangError='';shiguangLoading=true;try{adapters=await listShiguangAdapters(school.id);}catch(e){shiguangError=e instanceof Error?e.message:String(e);}finally{shiguangLoading=false;}}
  function backToSchools(){selectedSchool=null;adapters=[];shiguangError='';}
  async function beginShiguang(adapter: ShiguangAdapter){if(!selectedSchool||shiguangLoading)return;shiguangError='';shiguangLoading=true;sessionMessage='正在准备隔离的教务登录环境…';try{activeSession=await startShiguangImport(selectedSchool.id,adapter.adapterId);sessionMessage='登录窗口已打开。完成登录后会自动读取课程，不需要手动打开课表页面。';pollShiguang(activeSession.sessionId);}catch(e){shiguangError=e instanceof Error?e.message:String(e);sessionMessage='';}finally{shiguangLoading=false;}}
  async function pollShiguang(sessionId:string){if(pollTimer)clearTimeout(pollTimer);try{const state=await getShiguangSession(sessionId);sessionMessage=state.message||(state.status==='collecting'?'正在整理课程与作息…':'等待教务登录完成…');if(state.status==='complete'&&state.bundle){preview=state.bundle;selectedFile=`${state.schoolName} · ${state.adapterName}`;activeSession=null;shiguangOpen=false;selectedSchool=null;adapters=[];await closeShiguangSession(sessionId).catch(()=>undefined);return;}if(state.status==='error'){shiguangError=state.message||'拾光适配器执行失败。';activeSession=null;await closeShiguangSession(sessionId).catch(()=>undefined);return;}pollTimer=setTimeout(()=>pollShiguang(sessionId),900);}catch{sessionMessage='应用恢复后将继续检查导入结果…';pollTimer=setTimeout(()=>pollShiguang(sessionId),1500);}}
  function sourceAction(action:string){if(action==='shiguang')openShiguang();else if(action==='file')fileInput.click();}
  onDestroy(()=>{if(pollTimer)clearTimeout(pollTimer);});
</script>
<section class="page page-import"><header class="topbar"><div><span class="eyebrow">IMPORT HUB</span><h1>导入中心</h1><p>把不同来源的课程统一成一份可靠课表。</p></div></header>
<div class="import-hero glass-panel refract" class:drag-over={dragOver} on:dragover={(e)=>{e.preventDefault();dragOver=true;}} on:dragleave={()=>dragOver=false} on:drop={onDrop}><input bind:this={fileInput} class="file-input" type="file" accept=".json,.ics,.ical,.csv,.tsv,.cses,.yaml,.yml,.xls,.xlsx" on:change={(e)=>loadFile(e.currentTarget.files?.[0])}/><div class="upload-mark">{#if loading}<LoaderCircle class="spin" size={28}/>{:else}<UploadCloud size={28}/>{/if}</div><div><h2>{loading?'正在交给 Rust 解析…':'拖入课表文件，或点击选择'}</h2><p>自动判断 ICS / JSON / CSV / TSV / CSES；导入前始终预览差异，绝不直接覆盖现有课表。</p></div><button class="primary-button" on:click={()=>fileInput.click()} disabled={loading}>选择文件</button></div>
{#if committed}<div class="import-result import-success glass-panel"><CheckCircle2 size={18}/><div><b>导入完成</b><span>{committed}</span></div></div>{/if}{#if error}<div class="import-result import-error glass-panel"><X size={18}/><div><b>暂时无法解析 {selectedFile}</b><span>{error}</span></div></div>{/if}
{#if preview}<article class="import-preview glass-panel"><div class="preview-head"><div class="preview-ok"><CheckCircle2 size={20}/></div><div><span class="eyebrow">PARSE PREVIEW</span><h2>已识别 {preview.courses.length} 条课程记录</h2><p>{selectedFile} · 来源 {preview.source}</p></div><button class="icon-ghost" on:click={()=>preview=null}><X size={18}/></button></div><div class="preview-courses">{#each preview.courses.slice(0,6) as course}<div class="preview-course"><span>周{course.weekday}</span><div><b>{course.name}</b><small>第 {course.startSection}–{course.endSection} 节 · {course.location||'教室未提供'}</small></div><em>{course.weeks.length} 周</em></div>{/each}{#if preview.courses.length>6}<div class="preview-more">还有 {preview.courses.length-6} 条记录将在正式 Diff 页面中展示</div>{/if}</div><div class="preview-actions"><button class="secondary-button" on:click={()=>preview=null}>取消</button><button class="primary-button" on:click={commitPreview} disabled={loading}>确认并新建课表</button></div></article>{/if}
<div class="import-toolbar glass-panel"><Search size={18}/><input placeholder="搜索学校、教务系统或导入格式" on:focus={openShiguang}/><button><Link2 size={16}/> 粘贴链接</button></div>
<div class="source-grid">{#each sources as source}<button class="source-card glass-panel" on:click={()=>sourceAction(source.action)}><span class="source-icon {source.accent}"><svelte:component this={source.icon} size={22}/></span><div><span class="source-title"><b>{source.title}</b><em>{source.tag}</em></span><p>{source.subtitle}</p></div><ChevronRight size={18}/></button>{/each}</div>
{#if shiguangOpen}<div class="adapter-browser glass-panel refract"><div class="adapter-browser-head"><div class="adapter-brand"><span><Building2 size={20}/></span><div><span class="eyebrow">SHIGUANG COMPAT</span><h2>{selectedSchool?selectedSchool.name:'高校适配仓库'}</h2><p>{selectedSchool?'选择要执行的教务适配器':'实时读取 shiguang_warehouse 学校索引'}</p></div></div><button class="icon-ghost" on:click={()=>shiguangOpen=false}><X size={18}/></button></div>
{#if activeSession}<div class="adapter-session"><div class="session-orbit"><LoaderCircle class="spin" size={22}/></div><div><b>{activeSession.schoolName} · {activeSession.adapterName}</b><span>{sessionMessage}</span><small>会话仅允许访问：{activeSession.allowedHosts.join(' · ')}</small>{#if activeSession.insecureTransport}<small class="adapter-http-warning"><TriangleAlert size={13}/> 该校旧教务仍使用 HTTP，请尽量仅在可信校园网/VPN 中登录。</small>{/if}</div></div>
{:else if selectedSchool}<div class="adapter-subbar"><button on:click={backToSchools}><ArrowLeft size={15}/> 返回学校</button><span>{adapters.length} 个适配器</span></div><div class="adapter-list">{#if shiguangLoading}<div class="adapter-loading"><LoaderCircle class="spin" size={20}/> 正在读取学校适配器…</div>{:else}{#each adapters as adapter}<button class="adapter-row" on:click={()=>beginShiguang(adapter)} disabled={!adapter.importUrl}><span class="adapter-row-icon"><Globe2 size={18}/></span><div><b>{adapter.adapterName}</b><p>{adapter.description}</p><small>{adapter.category} · 维护者 {adapter.maintainer}</small></div><ChevronRight size={17}/></button>{/each}{#if !adapters.length}<div class="adapter-empty">这个学校暂时没有网页登录型适配器。</div>{/if}{/if}</div>
{:else}<div class="school-search"><Search size={17}/><input bind:value={schoolQuery} placeholder="输入学校名称，例如 广东工业大学 / GDUT"/><button on:click={async()=>{schools=[];await openShiguang();}}><RefreshCw size={15}/></button></div>{#if shiguangLoading}<div class="adapter-loading"><LoaderCircle class="spin" size={20}/> 正在从开放适配仓库拉取索引…</div>{:else}<div class="school-list">{#each filteredSchools as school}<button class:featured-school={school.id==='GDUT'} on:click={()=>chooseSchool(school)}><span>{school.initial.slice(0,1)||'校'}</span><div><b>{school.name}</b><small>{school.id}</small></div>{#if school.id==='GDUT'}<em>首个验证</em>{/if}<ChevronRight size={16}/></button>{/each}</div>{/if}{/if}
{#if shiguangError}<div class="adapter-error"><X size={15}/> {shiguangError}</div>{/if}<div class="adapter-sandbox-note"><ShieldCheck size={16}/><span>适配脚本只在隔离教务 WebView 中运行。课程先进入预览，不会直接覆盖你的课表。</span></div></div>{/if}
<div class="security-note glass-panel"><ShieldCheck size={19}/><div><b>适配器沙箱</b><span>默认仅允许声明过的 HTTPS 教务域名；旧系统只有在适配器明确声明时才允许 HTTP。Bridge 不提供本地文件或 Shell 权限。</span></div></div></section>
