<script lang="ts">
  import { ArrowRight, Bell, CloudSun, MapPin, MoreHorizontal, Navigation, Sparkles } from 'lucide-svelte';
  import CoursePill from '../components/CoursePill.svelte'; import type { Course } from '../types'; export let courses: Course[];
  $: todayCourses = courses.filter((course) => course.day === 1).slice(0, 5); $: nextCourse = todayCourses[2] ?? todayCourses[0] ?? courses[0];
</script>
<section class="page page-today">
  <header class="topbar"><div><span class="eyebrow">2026年9月7日 · 星期一</span><h1>下午好 <span>👋</span></h1><p>第一周 · 今天还有 {todayCourses.length} 节课</p></div><div class="top-actions"><button class="icon-button glass-panel"><Bell size={19} /></button><button class="avatar">K</button></div></header>
  <div class="hero-grid"><article class="next-card glass-panel refract"><div class="next-card-top"><span class="soft-badge"><Sparkles size={14} /> 下一节课程</span><button class="icon-ghost"><MoreHorizontal size={20} /></button></div><div class="next-main"><div><h2>{nextCourse?.name ?? '今天没有课程'}</h2><p><MapPin size={16} /> {nextCourse?.room || '自由安排'}{nextCourse?.teacher ? ` · ${nextCourse.teacher}` : ''}</p></div><div class="time-block"><b>{nextCourse?.start || '--:--'}</b><span>— {nextCourse?.end || '--:--'}</span></div></div><div class="progress"><i style="width:68%"></i></div><div class="next-bottom"><span>本地课表 · 离线可用</span><button>课程详情 <Navigation size={15} /></button></div></article><aside class="mini-card weather-card glass-panel"><div class="mini-icon"><CloudSun size={22} /></div><div><span>广州大学城</span><b>31°</b><small>天气模块接口预留</small></div></aside></div>
  <div class="section-heading"><div><h2>今天</h2><span>你的上课节奏</span></div><button>查看周课表 <ArrowRight size={15} /></button></div>
  <div class="today-content"><div class="timeline-card glass-panel"><div class="timeline-hours"><span>08</span><span>10</span><span>12</span><span>14</span><span>16</span><span>18</span></div><div class="timeline-line"><i style="left:61%"></i></div><div class="timeline-courses">{#each todayCourses as course}<CoursePill name={course.name} room={course.room || '教室待定'} time={course.start || `第${course.startSection}节`} color={course.color} />{/each}{#if !todayCourses.length}<div class="empty-day">今天没有课程，去做点自己的事。</div>{/if}</div></div><aside class="quick-stack"><button class="quick-card glass-panel"><span class="quick-orb orb-a"></span><div><b>本周 {courses.length} 个上课时段</b><small>自动按真实周次过滤</small></div><ArrowRight size={17} /></button><button class="quick-card glass-panel"><span class="quick-orb orb-b"></span><div><b>临时调整层</b><small>停课 / 补课 / 换教室不会破坏原课程</small></div><ArrowRight size={17} /></button></aside></div>
</section>
